#!/usr/bin/env bash
#
# Generated by dotdipper. Installs the tools this configuration expects.
#
# Synthesised from a Homebrew bundle and a Mac App Store inventory. It does
# not reproduce installed versions, the machine it was captured on, when it
# was captured, or applications installed by hand — none of that helps a new
# machine install tools, and a version list in particular tells a reader
# exactly which outdated builds to look up.
#
# Every step is idempotent, so re-running it is safe. A package that fails
# does not abort the run; failures are collected and reported at the end.

set -uo pipefail

log()  { printf '\033[0;32m[dotdipper]\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m[dotdipper]\033[0m %s\n' "$1" >&2; }
die()  { printf '\033[0;31m[dotdipper]\033[0m %s\n' "$1" >&2; exit 1; }

[[ "$(uname -s)" == "Darwin" ]] || die "This script targets macOS."

FAILED=()

# 2 entries from a personal tap were omitted: a tap, and the packages
# under it, name their owner, and this script is written to be
# shareable. Install those from your own machine instead.

TAPS=(
  'asmvik/formulae'
  'diegoholiveira/localports'
  'homebrew/services'
  'olets/tap'
  'railwaycat/emacsmacport'
  'romkatv/gitstatus'
  'supabase/tap'
)

FORMULAE=(
  'age'
  'asmvik/formulae/skhd'
  'asmvik/formulae/yabai'
  'azure-cli'
  'bat'
  'blueutil'
  'boost'
  'btop'
  'cloudflared'
  'cmake'
  'cmatrix'
  'coreutils'
  'diff-so-fancy'
  'docker'
  'edencommon'
  'exa'
  'fastfetch'
  'fb303'
  'fd'
  'fizz'
  'folly'
  'fzf'
  'gcc'
  'gh'
  'git'
  'git-filter-repo'
  'git-lfs'
  'gnu-sed'
  'gnutls'
  'go'
  'jq'
  'jupyterlab'
  'lazygit'
  'libpgm'
  'libpq'
  'libtensorflow'
  'libtiff'
  'little-cms2'
  'llvm'
  'lmdb'
  'mas'
  'mise'
  'neofetch'
  'neovim'
  'node'
  'nvm'
  'openjdk'
  'perl'
  'pkgconf'
  'pyenv'
  'python@3.10'
  'python@3.11'
  'python@3.12'
  'python@3.13'
  'rbenv'
  'render'
  'ripgrep'
  'ruby-build'
  'screenfetch'
  'tailscale'
  'telnet'
  'tmux'
  'vim'
  'vnu'
  'wangle'
  'watchman'
  'wget'
  'yarn'
  'zoxide'
  'zsh-autosuggestions'
  'zsh-syntax-highlighting'
)

CASKS=(
  'alacritty'
  'among-us'
  'antigravity'
  'appcleaner'
  'arc'
  'arduino-ide'
  'balenaetcher'
  'blackmagic-proxy-generator-lite'
  'bluestacks'
  'chatgpt'
  'claude'
  'cursor'
  'davinci-resolve'
  'discord'
  'docker-desktop'
  'dolphin'
  'dropzone'
  'eclipse'
  'emacs-app'
  'font-iosevka'
  'gcloud-cli'
  'ghostty'
  'google-chrome'
  'google-cloud-sdk'
  'grok-bot'
  'helium-browser'
  'istat-menus'
  'iterm2'
  'ivanti-secure-access'
  'karabiner-elements'
  'kitty'
  'logi-options+'
  'logseq'
  'microsoft-teams'
  'mos'
  'numi'
  'obsidian'
  'ollama-app'
  'omnidisksweeper'
  'orbstack'
  'orion'
  'postman'
  'rectangle'
  'rocket'
  'space-rabbit'
  'spotify'
  'superlist'
  't3-code'
  'tailscale-app'
  'tradingview'
  'visual-studio-code'
  'warp'
  'wezterm'
  'zed'
  'zen'
  'zoom'
)

MAS_IDS=(
  '310633997'
  '408981434'
  '409183694'
  '409201541'
  '409203825'
  '425424353'
  '462054704'
  '462058435'
  '462062816'
  '497799835'
  '682658836'
  '747648890'
  '937984704'
  '985367838'
  '990588172'
  '1287239339'
  '1388020431'
  '1540160809'
  '6469021132'
)

# 19 Mac App Store title(s), listed by id. `mas info <id>` names one.

if ! command -v brew >/dev/null 2>&1; then
  log "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" \
    || die "Homebrew installation failed."
  for candidate in /opt/homebrew/bin/brew /usr/local/bin/brew; do
    if [[ -x "$candidate" ]]; then eval "$("$candidate" shellenv)"; break; fi
  done
fi
command -v brew >/dev/null 2>&1 || die "Homebrew is installed but not on PATH."

for tap in ${TAPS[@]+"${TAPS[@]}"}; do
  log "Tapping $tap"
  brew tap "$tap" || FAILED+=("tap $tap")
done

for formula in ${FORMULAE[@]+"${FORMULAE[@]}"}; do
  if brew list --formula "$formula" >/dev/null 2>&1; then
    log "Already installed: $formula"
  else
    log "Installing $formula"
    brew install "$formula" || FAILED+=("brew $formula")
  fi
done

for cask in ${CASKS[@]+"${CASKS[@]}"}; do
  if brew list --cask "$cask" >/dev/null 2>&1; then
    log "Already installed: $cask"
  else
    log "Installing cask $cask"
    brew install --cask "$cask" || FAILED+=("cask $cask")
  fi
done

if [[ ${#MAS_IDS[@]} -gt 0 ]]; then
  if ! command -v mas >/dev/null 2>&1; then
    warn "mas is not installed; skipping Mac App Store titles."
  elif ! mas account >/dev/null 2>&1; then
    warn "Not signed in to the App Store; skipping Mac App Store titles."
    warn "Sign in, then re-run this script to install them."
  else
    for id in "${MAS_IDS[@]}"; do
      log "Installing App Store title $id"
      mas install "$id" || FAILED+=("mas $id")
    done
  fi
fi

# ---------------------------------------------------------------------------
# System and driver extensions.
#
# `brew install --cask` reports success once the app is in place, but an app
# that ships a driver extension is not finished at that point: macOS will not
# load the extension until a human approves it, and some apps do not even
# submit it for approval until the app itself has been run once. An unattended
# install therefore leaves a working-looking machine where the extension does
# nothing. Report that here rather than let it pass as success.
#
# This stage never activates anything. Activation opens a GUI approval dialog
# and, for Karabiner, a file:// URL — neither belongs in an unattended run.
# ---------------------------------------------------------------------------
extension_state() {
  systemextensionsctl list 2>/dev/null | grep -F "$1" | head -1
}

check_extensions() {
  command -v systemextensionsctl >/dev/null 2>&1 || return 0
  local pending=()

  # Any extension already known to macOS but not yet enabled is awaiting a
  # human. This catches every vendor, not just the ones named below.
  while IFS= read -r line; do
    case "$line" in
      *"[activated enabled]"*) ;;
      *"[activated"*|*"[terminated"*)
        pending+=("$(printf '%s' "$line" | awk -F'\t' '{print $4}')")
        ;;
    esac
  done < <(systemextensionsctl list 2>/dev/null | grep -E '^\*|^ ' || true)

  # Karabiner submits its DriverKit extension only when the app or its helper
  # runs, so a fresh unattended install leaves no row at all to detect.
  local km="/Applications/.Karabiner-VirtualHIDDevice-Manager.app/Contents/MacOS/Karabiner-VirtualHIDDevice-Manager"
  if [[ -x "$km" ]] && [[ -z "$(extension_state org.pqrs.Karabiner-DriverKit-VirtualHIDDevice)" ]]; then
    warn "Karabiner installed its driver extension but never submitted it."
    warn "  Run: \"$km\" activate"
    warn "  Then approve it, and note that Karabiner also needs Input Monitoring."
  fi

  if [[ ${#pending[@]} -gt 0 ]]; then
    warn "${#pending[@]} system extension(s) are installed but not enabled:"
    for ext in "${pending[@]}"; do warn "  $ext"; done
    warn "Approve them in System Settings > General > Login Items & Extensions."
  fi
}

[[ "$(uname -s)" == "Darwin" ]] && check_extensions

if [[ ${#FAILED[@]} -gt 0 ]]; then
  warn "${#FAILED[@]} item(s) did not install:"
  for item in "${FAILED[@]}"; do warn "  $item"; done
  exit 1
fi

log "All tools installed."
